[tool.black]
line-length = 79

[tool.pylint."MESSAGES CONTROL"]
enable = [
    "use-symbolic-message-instead",
    "useless-supression",
    "fixme",
]
disable = [
    "attribute-defined-outside-init",
    "duplicate-code",
    "invalid-name",
    "missing-docstring",
    "protected-access",
    "too-few-public-methods",
    "import-error",
    "no-value-for-parameter",
    "format",
]
